/cam_rgb:
  ros__parameters:
    device_name: /dev/cam_rgb
    camera_name: cam_rgb
    #YUYV/UYVY
    codec: MJPG
    fps: 60.0
    image_width: 640
    image_height: 480
    auto_white_balance: false
    auto_exposure: false
    exposure: 100
    white_balance: 4000
    show_img: false
    use_sensor_data_qos: false