/cam_thermal:
  ros__parameters:
    device_name: /dev/cam_thermal
    camera_name: cam_thermal
    #YUVY/UYVY
    codec: UYVY
    fps: 25.0
    image_width: 1280
    image_height: 512
    show_img: false
    use_sensor_data_qos: false